name: run example
on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: run custom actions
        id: test
        uses: Lycolia/swc-ts-custom-actions-example@8168506ea445299bfb80a2f3e6d38598f96fd532
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: show custom actions output
        run: echo ${{ steps.test.outputs.RESULT_MESSAGE }}
